server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/sportflow_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  # Una stringa casuale molto lunga (questa è in Hex, 256 bit). Mai metterla su GitHub nei progetti reali!
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # Durata del biglietto: 24 ore in millisecondi