server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/sportflow_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver