version: '3.8'

services:
  # --- DATABASE DEL BOOKING SERVICE ---
  postgres-booking:
    image: postgres:16-alpine
    container_name: sportflow-booking-db
    environment:
      - POSTGRES_DB=sportflow_booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-booking:/var/lib/postgresql/data

  # --- DATABASE DELL'AUTH SERVICE ---
  postgres-auth:
    image: postgres:16-alpine
    container_name: sportflow-auth-db
    environment:
      - POSTGRES_DB=sportflow_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

volumes:
  pgdata-booking:
  pgdata-auth: